import { deleteTransaction, upsertTransaction } from "@/lib/actions";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/data";
import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { formatCurrency } from "@/lib/utils";

export default async function TransactionsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const user = await requireUser(); const sp = await searchParams; const q = sp.q ?? ""; const type = sp.type;
  const transactions = await prisma.transaction.findMany({ where: { userId: user.id, ...(type ? { type: type as "INCOME" | "EXPENSE" } : {}), ...(q ? { OR: [{ description: { contains: q, mode: "insensitive" } }, { category: { contains: q, mode: "insensitive" } }] } : {}) }, orderBy: { [sp.sort ?? "date"]: sp.order === "asc" ? "asc" : "desc" } });
  return <div className="space-y-6"><h1 className="text-4xl font-black">Transactions</h1><Card><CardTitle>Add transaction</CardTitle><form action={upsertTransaction} className="mt-4 grid gap-3 md:grid-cols-6"><Input name="description" placeholder="Description" required/><Input name="category" placeholder="Category" required/><Input name="amount" type="number" step="0.01" placeholder="Amount" required/><select name="type" className="rounded-xl border bg-background px-3"><option>EXPENSE</option><option>INCOME</option></select><Input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/><Button>Save</Button></form></Card><Card><form className="mb-4 flex flex-wrap gap-3"><Input name="q" defaultValue={q} placeholder="Search" className="max-w-xs"/><select name="type" defaultValue={type ?? ""} className="rounded-xl border bg-background px-3"><option value="">All</option><option>EXPENSE</option><option>INCOME</option></select><select name="sort" defaultValue={sp.sort ?? "date"} className="rounded-xl border bg-background px-3"><option value="date">Date</option><option value="amount">Amount</option><option value="category">Category</option></select><Button>Filter</Button></form><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-muted-foreground"><th className="py-3">Date</th><th>Description</th><th>Category</th><th>Type</th><th className="text-right">Amount</th><th></th></tr></thead><tbody>{transactions.map((t) => <tr key={t.id} className="border-t"><td className="py-3">{t.date.toISOString().slice(0,10)}</td><td>{t.description}</td><td>{t.category}</td><td>{t.type}</td><td className="text-right font-semibold">{formatCurrency(Number(t.amount), user.currency)}</td><td className="text-right"><form action={deleteTransaction}><input type="hidden" name="id" value={t.id}/><Button variant="ghost">Delete</Button></form></td></tr>)}</tbody></table></div></Card></div>;
}
