import { differenceInMonths } from "date-fns";
import { deleteGoal, upsertGoal } from "@/lib/actions";
import { getFinancialSnapshot, requireUser } from "@/lib/data";
import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { formatCurrency, pct } from "@/lib/utils";

export default async function GoalsPage() { const user = await requireUser(); const data = await getFinancialSnapshot(user.id); return <div className="space-y-6"><h1 className="text-4xl font-black">Savings goals</h1><Card><CardTitle>Create goal</CardTitle><form action={upsertGoal} className="mt-4 grid gap-3 md:grid-cols-5"><Input name="name" placeholder="Emergency fund, vacation..." required/><Input name="targetAmount" type="number" placeholder="Target" required/><Input name="currentAmount" type="number" placeholder="Current" required/><Input name="deadline" type="date" required/><Button>Save goal</Button></form></Card><div className="grid gap-4 md:grid-cols-2">{data.goals.map((g) => { const progress = Number(g.currentAmount)/Number(g.targetAmount)*100; const months = Math.max(1, differenceInMonths(g.deadline, new Date())); const contribution = (Number(g.targetAmount)-Number(g.currentAmount))/months; return <Card key={g.id}><CardTitle>{g.name}</CardTitle><p className="mt-2 text-sm text-muted-foreground">Deadline {g.deadline.toISOString().slice(0,10)} • estimated {formatCurrency(contribution, user.currency)}/mo</p><div className="mt-4"><Progress value={progress}/></div><p className="mt-2 font-semibold">{formatCurrency(Number(g.currentAmount), user.currency)} / {formatCurrency(Number(g.targetAmount), user.currency)} ({pct(progress)})</p><form action={upsertGoal} className="mt-4 grid gap-2"><input type="hidden" name="id" value={g.id}/><Input name="name" defaultValue={g.name}/><Input name="targetAmount" type="number" step="0.01" defaultValue={Number(g.targetAmount)}/><Input name="currentAmount" type="number" step="0.01" defaultValue={Number(g.currentAmount)}/><Input name="deadline" type="date" defaultValue={g.deadline.toISOString().slice(0,10)}/><Button variant="secondary">Update</Button></form><form action={deleteGoal} className="mt-2"><input type="hidden" name="id" value={g.id}/><Button variant="ghost">Delete</Button></form></Card>; })}</div></div>; }
