import { deleteInvestment, upsertInvestment } from "@/lib/actions";
import { AllocationBar, CategoryPie } from "@/components/charts/finance-charts";
import { getFinancialSnapshot, requireUser } from "@/lib/data";
import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { formatCurrency } from "@/lib/utils";
import { getUserDictionary } from "@/lib/i18n";

export default async function InvestmentsPage() { const user = await requireUser(); const t = await getUserDictionary(user.id); const data = await getFinancialSnapshot(user.id); const allocation = Object.values(data.investments.reduce<Record<string,{name:string;value:number}>>((a,i)=>{a[i.type]??={name:i.type,value:0}; a[i.type].value += Number(i.quantity)*Number(i.currentPrice); return a;},{})); const pnl = data.investments.reduce((s,i)=>s+(Number(i.currentPrice)-Number(i.purchasePrice))*Number(i.quantity),0); return <div className="space-y-6"><h1 className="text-4xl font-black">{t.investments}</h1><div className="grid gap-4 md:grid-cols-3"><Card><p className="text-sm text-muted-foreground">{t.portfolioValue}</p><p className="text-3xl font-black">{formatCurrency(data.investmentValue,user.currency)}</p></Card><Card><p className="text-sm text-muted-foreground">{t.profitLoss}</p><p className={pnl>=0?"text-3xl font-black text-emerald-500":"text-3xl font-black text-red-500"}>{formatCurrency(pnl,user.currency)}</p></Card><Card><p className="text-sm text-muted-foreground">{t.mockPricingMode}</p><p className="text-xl font-bold">{t.mockPricingEnabled}</p></Card></div><Card><CardTitle>{t.addHolding}</CardTitle><form action={upsertInvestment} className="mt-4 grid gap-3 md:grid-cols-7"><Input name="assetName" placeholder="Asset" required/><Input name="symbol" placeholder="Symbol" required/><select name="type" className="rounded-xl border bg-background px-3"><option>STOCK</option><option>ETF</option><option>CRYPTO</option><option>CASH</option></select><Input name="quantity" type="number" step="0.000001" placeholder="Qty" required/><Input name="purchasePrice" type="number" step="0.01" placeholder="Buy" required/><Input name="currentPrice" type="number" step="0.01" placeholder="Current" required/><Button>{t.save}</Button></form></Card><div className="grid gap-4 xl:grid-cols-2"><Card><CardTitle>{t.assetAllocation}</CardTitle><CategoryPie data={allocation}/></Card><Card><CardTitle>{t.performanceByAsset}</CardTitle><AllocationBar data={data.investments.map(i=>({name:i.symbol,value:(Number(i.currentPrice)-Number(i.purchasePrice))*Number(i.quantity)}))}/></Card></div><Card><table className="w-full text-sm"><tbody>{data.investments.map(i=><tr key={i.id} className="border-t"><td className="py-3 font-semibold">{i.assetName} ({i.symbol})</td><td>{i.type}</td><td>{Number(i.quantity).toString()} × {formatCurrency(Number(i.currentPrice),user.currency)}</td><td className="text-right">{formatCurrency(Number(i.quantity)*Number(i.currentPrice),user.currency)}</td><td><form action={deleteInvestment}><input type="hidden" name="id" value={i.id}/><Button variant="ghost">{t.delete}</Button></form></td></tr>)}</tbody></table></Card></div>; }
