import { startOfMonth } from "date-fns";
import { deleteBudget, upsertBudget } from "@/lib/actions";
import { getFinancialSnapshot, requireUser } from "@/lib/data";
import { Button } from "@/components/ui/button";
import { Card, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { formatCurrency, pct } from "@/lib/utils";

export default async function BudgetsPage() { const user = await requireUser(); const data = await getFinancialSnapshot(user.id); const month = startOfMonth(new Date()).toISOString().slice(0,10); return <div className="space-y-6"><h1 className="text-4xl font-black">Budgets</h1><Card><CardTitle>Monthly budget</CardTitle><form action={upsertBudget} className="mt-4 grid gap-3 md:grid-cols-4"><Input name="category" placeholder="Category" required/><Input name="limit" type="number" step="0.01" placeholder="Limit" required/><Input name="month" type="date" defaultValue={month}/><Button>Save budget</Button></form></Card><div className="grid gap-4 md:grid-cols-2">{data.budgets.map((b) => { const spent = data.transactions.filter((t) => t.type === "EXPENSE" && t.category === b.category && t.date >= b.month).reduce((s,t)=>s+Number(t.amount),0); const usage = spent / Number(b.limit) * 100; return <Card key={b.id}><div className="flex justify-between"><CardTitle>{b.category}</CardTitle><span className={usage >= 100 ? "text-red-500" : usage >= 80 ? "text-amber-500" : "text-muted-foreground"}>{usage >= 100 ? "Exceeded" : usage >= 80 ? "Close to limit" : "On track"}</span></div><p className="mt-2 text-sm text-muted-foreground">{formatCurrency(spent, user.currency)} of {formatCurrency(Number(b.limit), user.currency)}</p><div className="mt-4"><Progress value={usage} tone={usage >= 100 ? "danger" : usage >= 80 ? "warn" : "primary"}/></div><p className="mt-2 text-sm font-semibold">{pct(usage)} used</p><form action={upsertBudget} className="mt-4 grid gap-2"><input type="hidden" name="id" value={b.id}/><Input name="category" defaultValue={b.category}/><Input name="limit" type="number" step="0.01" defaultValue={Number(b.limit)}/><Input name="month" type="date" defaultValue={b.month.toISOString().slice(0,10)}/><Button variant="secondary">Update</Button></form><form action={deleteBudget} className="mt-2"><input type="hidden" name="id" value={b.id}/><Button variant="ghost">Delete</Button></form></Card>; })}</div></div>; }
